### ISSUE TITLE
Select programming language for OVN

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#196]
As we are approaching creating VRS a POC, we need to start looking at the programming language for VRS.

Option 1. Java
Option 2. GoLang
Option 3. Rust

The expectation for this issue is to come up with the pros and cons for each option on the table.

**Comment by maridob** [comment]
CC: @gpradeep-target , @rogerkibbe , @jaykline

**Comment by maridob** [comment]
Doug Rogers to Everyone (9:34 AM)
I vote for Rust....love the enhanced security capabilities

**Comment by slushpupie** [comment]
I vote for Rust

**Comment by pmotch** [comment]
Rust.

From my pitch:
- The hand wavy stuff (but still important): "Rust is every bit as important a revolution as C" - Bryan Cantrill
- Safety
- Rich standard lib, but able to opt of of it
  - This is important for us given many things are standards for components that we will possibly host on embedded devices (virtual assistants, etc) where memory is thin (e.g. 32k); we'll be able to do this because with Rust you can opt out of the std lib and compile to smaller targets
  - Being able to use the same lang we'll use for system programming (components we write on normal computers) and use it also for embedded level development means fewer languages, which means more people to review PRs, contribute, etc.
- In good company with others: companies using it more (Target, Microsoft, etc -- see regular news about this), lots of developers showing interest and job market growing, in-roads to places where other languages haven't been before (Linux kernel, embedded development, etc)

**Comment by iotmnovak** [comment]
Vote #2 for Rust.    (rust never sleeps....)
  
  
  
  

  Digital Business Exec   

  

      
  

  
  
>

**Comment by Jim1151** [comment]
We should ask our sponsers what their preference is.  We don't want to surprise them down the road when we suddenly release code written in a new language they were not aware of.

**Comment by ToddE** [comment]
Assuming this if for a SDK, but the structure of OVN should ideally be API-based to allow maximum flexibility. Many voice systems are built with C on yocto embedded systems. Look at platforms such as those provided by[ StreamUnlimited](https://www.streamunlimited.com/hardware-modules/), [Linkplay ](https://www.linkplay.com/modules) and [Sugr](https://www.sugrsugr.com/sugrsense) to understand what hardware is being used by systems integrators in this space (and perhaps try to get sponsorship from some or all of them). StreamUnlimited is partially owned by Google (but Google does not interfere with their tech stack or development practices)  and does a lot of work with Alexa products and has been developing multi-voice solution prototypes for several years now. Their StreamSDK has been used by other integrators and companies in this space as well. Hardware affordability/competitiveness is a key to adoption in this space.

**Comment by rogerkibbe** [comment]
I think Solidity is the right choice - just kidding. 🤣 

No deep concerns here or strong preferences frankly as I think a robust system could be built with any of the proposed languages. That being said, I think Rust is a fine choice and certainly a good choice for a low latency, DNS like system like VRS.

I agree we should sync with sponsors around the language preference.

Whatever we do, I assume it will be open source.

**Comment by gpradeep-target** [comment]
I vote for Rust.

We will have some learning to do, if majority of the developers are not familiar with Rust.

**Comment by maridob** [comment]
Decision: RUST 

Accepting the known risk of the learning curve.
