### ISSUE TITLE
Alternatives names scenario

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#96]
**PROBLEM**
Discuss the solution options on how can VRS help in solving the alternatives names scenarios (disambiguation #56 #64)
Example: "Tarjey" = "Target"; "Delta" = "Delta Dental"

This is different from mispronunciation.

**DOD**
- [ ] Identify the possible options for the alternative 
- [ ] Make a recommendation the best path forward

**Comment by maridob** [comment]
Pradeep

**Comment by gpradeep-target** [comment]
Three concerns that lead to ambiguity (alternate names):

1. Homophones (diff spelling, same pronounciation) e.g Sysco vs Cisco
2. Homographs (same spelling, diff meaning)
3. Mispronounciation - could be due to unfamiliarity, locale, possible physical disability etc.


**Homophones & Homographs**
One of the approaches is to provide the user the possible options in a specific order (or based on descending order of confidence score), and let the user pick his or her choice.

**_Pros:_** Simple and Intuitive approach for the user
**_Cons:_** Implementation and Support might be a challenge where the channel (device) needs to perform additional work like reading the options to the user, and taking appropriate action.

**Improving the efficiency to reduce ambiguity.**
_1. Use locale_ 
Use additional information from the channel (device) and tag it as a parameter to the NLU model to determine the appropriate result

_2. Use user's history_
Use user history (if available and permitted) to suggest the best match

_3. Provide user with one option at a time_
Display the first option (highest confidence factor), and if user rejects the same, provide the next one.

**Mispronounciation**
Handling this scenario could be a challenge and could also frustrate the user if he or she has to go through multiple rounds before the VRS understands what the user is looking for.

Unfamiliarity and Physical disability (voice) may not be handled gracefully at all.

However locale specific Mispronounciation or language accent can be handled by training the NLU model (if one is supported) with locale as a parameter.

**Comment by maridob** [comment]
**Today's Meeting notes :**
- Should we include "category" as part of the VRS capabilities?
- ACTION: Need to create the architecture decision to understand how VRS will play a role on the alternatives name scenario? @gpradeep-target

**Comment by gpradeep-target** [comment]
@maridob bought up an important point that I had missed - VRS is not concerned with the voice transformation i.e. voice to text.  The voice to text transformation is performed by the fronting device, app, etc., VRS receives only the text, and VRS's responsibility is to map this text to an appropriate matching entity and it's associated endpoint.

Depending on the pronunciation and transformation an entity might be spelled differently (homographs, aliases, mispronunciation etc.) or same pronunciation might map to more than one entity (homophones).  The VRS essentially should map the text it receives to the matching entity name and return the same.

With the above scenario it is possible that an entity might be spelt in more than one form, hence VRS should take into account all these alternate spellings.  Let's call them as PRIMARY form and SECONDARY forms.  The PRIMARY form represents the entity's primary name, which is always one; and SECONDARY forms represent alternate names the entity is known by.  VRS should handle searches by both PRIMARY and SECONDARY form.

With this arises another possibility where an entity registers SECONDARY forms, and one or more of these forms happen to be the PRIMARY form of another entity.  This needs to be resolved as well.

e.g. Cisco.  PRIMARY form --> Cisco, SECONDARY forms --> Sysco, SisCo.  Here Sysco is a another entity, VRS would have a conflict when Sysco tries to register with its PRIMARY form.

Post our discussion, will put in place the ADR.

**Comment by maridob** [comment]
Discussing this issue 04.29.2021

OPTION 1. Create a relationship with the same record. 
example:
{ record: 1
  record_name: Cisco Network
  alternative_names: Cisco
 ...
}

PROS:
1. 

CONS


OPTION 2. Create 2 records 
example:
{ record: 1
  record_name: Cisco Network
 ...
}
{
record: 2
  record_name: Cisco
}

**Comment by gpradeep-target** [comment]
Evaluating Option 1 and Option 2 under following headings:
1. Maintenance - Each record holds data in addition to the record_name, every correction/update will be based on the record_name.
  Option 1: Update happens simply by identifying the record_name and update the record data
  Option 2: Search all records (that uses alternate_name) belonging to the record_name and update the same. This would require storing the mapping in both the records.  Updating will require searching updating multiple records.
2. Corrections - Let us pick Cisco as an example.  ‘Cisco’ is the record_name, and ‘Sysco’ is the alternative_names.  Suppose Sysco is a different entity, and its business owner would like to claim ‘Sysco’ as its record_name.
    Option 1: The fix is to remove ‘Sysco’ from alternative_names under Cisco record.  And searching a record for edit is easy because the search is on ’Cisco’
    Option 2: The fix is to remove 'Sysco' from the record list.  And update mapping between Cisco and Sysco
3. Storage - The system will need to use two types of storage (for performance) - a persistent storage (like DB) and an in-memory storage (cache).  A forward cache is the ideal way to implement the system.  All read (search) operations go to cache, while all update (write/update/delete) go to cache and DB (with enough safeguards to ensure data integrity)

DB: Supports both Options - Option 1 is simpler to update records.
Cache: The chosen Option will have an impact here:
    Option 1: Will need two caches:
        a. Cache 1 - (Key, Value) --> (record_name/alternative_name, record_id/record_no)
        b. Cache 2 - (Key, Value) --> (record_id/record_no, record_data)
        Pros: Updates are simple
        Cons: Search requires two hits on Cache        
    Option 2: Single cache:
        a. Cache 1 - (Key, Value) --> (record_name/alternate_name, record_data)
        Pros: Search requires one hit on Cache - simple
        Cons: Updates require - updating multiple records

Conclusion: Option 1 has more merits in terms of maintaining the system, while Option 2 is better from search perspective.  Consider Option 1 to store in DB, and Option 2 in Cache.

**Comment by maridob** [comment]
Based on swagger design, that we will treat the alternative names as separate record and keep it simple.
We will wait feedback from the Conversational Platform (i.e., Deutsche Telekom) for phase 1 approach.
